### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by browski1** [petercunha/Pine#12]
I try to get this to work on windows since some time now but i cant handle this error

File "C:\Windows\system32\lib\pine.py", line 14, in <module>
   from lib.grab import grab_screen
ModuleNotFoundError: No module named 'lib.grab'

i already installed grab_screen via pip

**Comment by petercunha** [comment]
lib.grab is referencing [this file](https://github.com/petercunha/Pine/blob/master/lib/grab.py) in the "lib" folder of this repo.

Make sure you're running pine.py from the base directory, not the lib directory.
