### ISSUE TITLE
Only moves cursor?

### ISSUE THREAD

**Issue by Fightfrog** [petercunha/Pine#2]
is it right that it only moves the cursor? As it wasnt sending input to any actual games.

Else nice job. Is it just trainend with csgo models?

**Comment by petercunha** [comment]
Yes it only moves the cursor. You *may* have to run it as administrator for it to send inputs to the game. Also try toggling "Raw Input" in CS:GO if it's not moving the crosshair.

Yes, trained on CS:GO and COCO datasets!

**Comment by Fightfrog** [comment]
Weird, i had to turn RawInput off in CSGO for it to work. In some other games it wont move the crosshair even though its detecting things.
Also still getting this: https://gyazo.com/837e46dbbd4f98950628bee98019abef
and CUDA wont work.

Extra Questions:
You plan on creating more/better datasets or show how one can create them for certain games?!?
You plan on updating the aimbot part of your aimbot? It needs some kind of smoothing settings; on/off switch; ON when key is held; autoshot (after detecting enemy and moving xhair); Where to hit? head, body, both/closest
I never worked with python, but worked with autoit and ahk a lot and most of it seems doable.

**Comment by petercunha** [comment]
@Fightfrog I'm very busy with projects and midterms for school, but when I have free time in a few weeks I plan on continuing development. I'll definitely add your suggestions / bug reports to the roadmap.

BTW: For CUDA to work, you need to have compiled OpenCV with CUDA bindings.

**Comment by Fightfrog** [comment]
Thanks for your reply. First ill try to get OpenCV with CUDA bindings running as that didnt seem to be too easy.
If i get that working ill see how far i can get rewriting some stuff.
