### ISSUE TITLE
The Aimbot aims at the ground in CSGO.

### ISSUE THREAD

**Issue by MissXLina** [petercunha/Pine#27]
Hey everybody, 

in CSGO, every time when the screen-capture sees an enemy, it automatically aims at the ground. I got CUDA and cuDNN installed.

I added a picture of the console window.

I'm on a RTX 2060, if that causes any problem.

![Unbenannt](https://user-images.githubusercontent.com/61363222/82509879-69303780-9b09-11ea-9d5d-6dbcfb726a7b.PNG)

**Comment by petercunha** [comment]
Please toggle raw-input in CS:GO settings, it should fix the problem

**Comment by MissXLina** [comment]
I already solved it. But thank you still. ^^
