### ISSUE TITLE
30FPS

### ISSUE THREAD

**Issue by henceiusegentoo** [petercunha/Pine#28]
Hey everybody,

i got the problem, that i only get 30FPS with CUDA and cuDNN installed.

I got a RTX 2060 with the newest Game Ready drivers.

What can I do? I added a screenshot of the console window.
![Unbenannt](https://user-images.githubusercontent.com/61363222/82510718-9382f480-9b0b-11ea-9394-e6a1f98c1d6e.PNG)

The 60FPS you see are because CSGO isn't opened.

**Comment by FidgetySo** [comment]
First of all that is really good without cuda i get 12 fps and that is okay so don't complain you ain't going to get much better
