### ISSUE TITLE
I got a little bug

### ISSUE THREAD

**Issue by Hihru** [petercunha/Pine#3]
Traceback (most recent call last):
  File "C:\Users\test\Desktop\Pine-master\Pine-master\pine.py", line 13, in <module>
    pine.start(ENABLE_AIMBOT=True)
  File "C:\Users\test\Desktop\Pine-master\Pine-master\lib\pine.py", line 77, in start
    print(colored("[OKAY] Aimbot enabled!", "green"))
TypeError: 'module' object is not callable

how i can fix this problem ?

**Comment by Hihru** [comment]
i delete this in the start file pine.start(ENABLE_AIMBOT=True) then i got no wrong message but i think the programm start and close too fast what can i do ?

**Comment by Hihru** [comment]
I work with Python 3.7 i have installed all so i think sry for my bad english!

best regards
Hihru

**Comment by petercunha** [comment]
Hmm, what terminal and OS are you using?

**Comment by Hihru** [comment]
I use Windows 10 (1803) 64Bit and i use Python 3.7 IDLE MODE too load.

**Comment by petercunha** [comment]
It's possible that "idle" doesn't support colored output. Could you try running this in cmd with:
`python pine.py`

**Comment by Hihru** [comment]
Dont work mhh i have cuda 10.1 GTX 1080 which system have u ? i try it with windows power shell as admin and i try it in cmd dont work for me

**Comment by petercunha** [comment]
It runs fine for me with Python 3.7 on my Mac, Windows, and Linux computers. I think this is a problem with your specific environment.
