### ISSUE TITLE
How do I build OpenCV with CUDA?

### ISSUE THREAD

**Issue by Flodkozza** [petercunha/Pine#4]
When I build OpenCV and while it's building it says "CUDA: YES" but I am not sure if CUDA is built properly. I followed a couple of tutorials but it's always the same. Also I don't get a cv2.pyd like other people do so I'm not sure how to even import it into python.
My OS is Windows 10..

**Comment by petercunha** [comment]
The build process is pretty complex, it's not easy to do. 
I recommend this guide: https://jamesbowley.co.uk/build-opencv-4-0-0-with-cuda-10-0-and-intel-mkl-tbb-in-windows/#python_bindings

**Comment by Flodkozza** [comment]
I sucessfully installed OpenCV with CUDA and it also says "[OKAY] CUDA is working!" but my FPS is exactly the same as before ~12.

**Comment by Flodkozza** [comment]
Also it usually detects like the inner part of an enemy so it aims at their hips instead of their head..
![image](https://user-images.githubusercontent.com/25553732/56195393-2ca42980-6035-11e9-85cc-9c6228daf063.png)
