### ISSUE TITLE
Aims at ground

### ISSUE THREAD

**Issue by hi-204** [petercunha/Pine#44]
I tried this hack in apex and it works on the menu (aims to the selected character) but it will aim to the ground when targeting a player. Do i have to retrain it? If so how do I go about that? I'm new to this kind of thing.

**Comment by danielboos1** [comment]
Turn off raw input. I have the same problem with rainbow even with raw turned off but it fixed csgo so

**Comment by danielboos1** [comment]
I have found less popular projects that are much better designed than this one, I'll be giving them a test
