### ISSUE TITLE
Only 12 FPS with Cudnn and OpenCL enabled

### ISSUE THREAD

**Issue by Flodkozza** [petercunha/Pine#5]
I only have 12 FPS even I have everything enabled and its green when I start the script. The aimbot moves so slowly ( because of the low FPS?)

**Comment by DJPlaya** [comment]
Having the same Issues on an AMD R9 390x - 5-6fps
What i am wondered about is that the GPU usage is on 20% and CPU and Memory are also fine, so i cannot imagine the Source of this

**Comment by petercunha** [comment]
The recent Nvidia driver updates seemed to have fixed this. I'm getting pretty high FPS on a GTX 1070. Please update your drivers.

**Comment by DJPlaya** [comment]
My AMD Driver is on the latest Stable Build and ime still having this Issue

**Comment by petercunha** [comment]
CUDA acceleration does not work with AMD hardware. Sorry.

**Comment by DJPlaya** [comment]
So you want to fully drop the support for AMD?
I have profiled my System a bit and its definitely not an Issue of Resources

**Comment by petercunha** [comment]
That's not what I said... AMD is still supported via OpenCL.

Pine is just better optimized for Nvidia hardware.

**Comment by DJPlaya** [comment]
Okay, but still this is an bigger Issue, Pine seems to be currently unusable on AMD GPUs.
If you plan to better implement OpenCL and need Hardware to test it i can provide you with a remote System

**Comment by Flodkozza** [comment]
I tested it once again, first without Cuda and then with it, both have about 30 FPS. If I use darknet C framework, with tiny yolo I get about 200 FPS with CUDA. So still not working for me. ( Does say CUDA ENABLED in the console )

**Comment by petercunha** [comment]
@Flodkozza keep in mind there are other limiting factors to FPS, including continuously taking screenshots of your monitor to analyze.

It's possible that the neural net is fast but it's being bounded by the time it takes to capture your screen. I will have to do some benchmarking to find out.
